# Site settings
title: F. Yannick Zehnder
email: contact@yannickzehnder.ch
url: http://yannickzehnder.ch
description: "Co-founder & CEO at CEVEN, techaer, advisor."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: F. Yannick Zehnder

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/yannickzehnder/ 
  - title: twitter
    url: https://twitter.com/yannickzehnder
  - title: github
    url: https://github.com/fyzehnder

# Build settings
markdown: kramdown
permalink: pretty
